server:
  port: 8090

spring:
  config:
    activate:
      on-profile: local

  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    url: jdbc:postgresql://localhost:5432/quizup_matchmaking
    username: postgres
    password: postgres

logging:
  level:
    io.github.quizup: DEBUG

